name: Pull request checks

on:
  pull_request:
    branches: 
      - master

jobs:
  pr-checks:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.8.0
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: test
        run: yarn test
