name: ci
on:
  push:
    branches:
      - master
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.8.0
    - name: install
      run: yarn
    - name: build
      run: yarn build
    - name: test
      run: yarn test
    - name: release
      env:
        AID: ${{ secrets.AID }}
        AIP: ${{ secrets.AIP }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      run: yarn release # electron-builder --publish always

  # build_on_win:
  #   runs-on: windows-2016
  #   steps:
  #   - uses: actions/checkout@master
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 12.8.0
  #   - name: install
  #     run: yarn
  #   - name: build
  #     run: yarn build
  #   - name: test
  #     run: yarn test
  #   - name: release
  #     env:
  #       GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #     run: yarn release
